Player control
T4g1/gd-wildjam18 pull request #12
Opened 2020-02-16 12:35 UTC by tienlocnguyen

Main purpose of this PR is control player. I also implement simple scene to test it. Test scene can be used for action level, but it simple and quality is not really good.

2020-02-16 13:57 UTC, T4g1 requested changes
- Please remove warnings and debug printing (12 warnings and many more debug print)
- Some inconsistency when moving player: If I press left then right and stay on those: Player goes left. If I press right then left, player goes left (behavior expected is to stay going right then): I suggest to stop when both key are pressed.
- Pressing up once will make the player jump if held too much: Can trigger unwanted jumps

2020-02-16 14:02 UTC, T4g1 commented
Also the test scene should probably not be part of it right now (we don't want debug things on master?)

2020-02-16 14:27 UTC, tienlocnguyen commented
> Also the test scene should probably not be part of it right now (we don't want debug things on master?)
Yes, it's for test only. I'll remove it.

2020-02-16 14:53 UTC, tienlocnguyen commented
> * much

I fixed point 1 and 2. Still have workaround to fix warning in signal handle(some param). It will be updated later when have enough game entity like obstacles
Point 3 is not clear. I hold up button but there's no unwanted jump. In my code, player only jump when he's not jumping

2020-02-16 18:01 UTC, T4g1 requested changes
About the jumping logic: Wouldn't it be better to push the up button to stand and not jump if we hold it? When pressing the first time, player want to stand, not jump, thats why I believe, jumping after a delay makes it inconsistent with player expectation

About the crouching: Is it necessary to hold the crouching stance when crouch is not held? As we are designing a running/action scene and not a shooter, I believe Player need to stand up as fast as possible  (implying speed is reduced in crouching stance)

About DeathHole: Wouldn't it be better to separate the DeathHole logic from the player?

Side note: You can use https://docs.godotengine.org/en/3.2/classes/class_area2d.html#class-area2d-method-get-overlapping-bodies with StandShape instead of relying on multiple signals and counter

Also for simplification, I recommend you this: https://docs.godotengine.org/en/3.2/tutorials/2d/2d_movement.html#way-movement Where they separate input logic and movement logic (right now, the whole movement/jump/crouch/input logic is closely interwinned which makes it difficult to understand)

2020-02-16 18:01 UTC, T4g1 commented on project.godot
> +2d_physics/layer_12="PayerStandShape"
Why do we need two layers for the player?
What is a Pipe? Why is an "obstacle" layer not enough for Pipe and DeathHole?
What is DeathHole?

2020-02-16 18:01 UTC, T4g1 commented on project.godot
> +2d_physics/layer_12="PayerStandShape"
What I believe should be enough is:
Player, Obstacle, Trigger (or Area)

2020-02-16 18:01 UTC, T4g1 commented on sources/player/Player.tscn
> +position = Vector2( 150, 97 )
Typo? You probably want player to be centered by default with no offset (0; 0)

2020-02-16 18:01 UTC, T4g1 commented on sources/player/Player.tscn
> +position = Vector2( 150, 97 )
Same here

2020-02-16 18:01 UTC, T4g1 commented on sources/player/Player.tscn
> +position = Vector2( 150, 96 )
And here

2020-02-17 01:38 UTC, tienlocnguyen commented on sources/player/Player.tscn
> +position = Vector2( 150, 97 )
I used editor and move player around. So I don't note this change. Will update it

2020-02-17 01:38 UTC, tienlocnguyen commented on sources/player/Player.tscn
> +position = Vector2( 150, 97 )
Same as above

2020-02-17 01:38 UTC, tienlocnguyen commented on sources/player/Player.tscn
> +position = Vector2( 150, 96 )
Same as above

2020-02-17 02:01 UTC, tienlocnguyen commented on project.godot
> +2d_physics/layer_12="PayerStandShape"
Sorry for my English. I lacked some vocabularies.
About 2 layers for players: I need 2 collide shapes for players:
- One is player shape which change when he stand, crouch
- One is shape when he stand. I used it to make sure player can stand while he is crouching. For example, when he enter a location that not high enough to stand but enough to crouch, he can't stand any more
![image](https://user-images.githubusercontent.com/6823008/74617947-4b49e400-5162-11ea-81bf-742c20821a5e.png)
Pipe is think that player can jump up to run
DeathHole: When player collide it, player die. My idea is a death hole will move after player, so player need move continuously.

For player movement, I base on demo in: https://github.com/godotengine/godot-demo-projects/blob/master/2d/kinematic_character/player.gd. Seem that it have some update compare with my local version

2020-02-17 08:59 UTC, T4g1 commented on project.godot
> +2d_physics/layer_12="PayerStandShape"
Yeah but the point is: Why not put Pipe in an Obstacle layer (along with floor and so on). Standing shape and Death Hole in a Trigger layer? And Player body in the Player layer?

2020-02-17 19:14 UTC, T4g1 requested changes
Way better, I commented with what cannot go on master and here are some general tips: Its somewhat unclear what most of the function do. Adding a few comments could help. For example, do we want a function to jump the player or a function to try_to_jump?

Also, the coding conventions are inconsistent: Naming is sometimes camelcase, uppercase, short, long. What is a vlen? or a vsign? Why not use velocity_sign for example (if it's indeed what you mean by vsign)
There is a method named my_method and a variable named on_air_time which is inconsistent too

2020-02-17 19:14 UTC, T4g1 commented on project.godot
> +2d_physics/layer_1="Platform"
Renaming the layers already defined is probably not what you wanted to do here. Use layer after the third one if you need more (but again, do we need a layer for Wall and Platform? Obstacle isn't enough? Is this relevant to player movement?

2020-02-17 19:14 UTC, T4g1 commented on sources/player/Player.gd
> +	velocity += force * delta
Regarding move_and_slide: https://docs.godotengine.org/en/3.1/classes/class_kinematicbody2d.html#class-kinematicbody2d-method-move-and-slide You should not multiply it by delta, its already taken care of.

2020-02-17 19:14 UTC, T4g1 commented on sources/player/Player.tscn
> +position = Vector2( 150, 97 )
Still relevant here

2020-02-17 19:14 UTC, T4g1 commented on sources/player/Player.tscn
> +position = Vector2( 150, 97 )
And here

2020-02-17 20:45 UTC, T4g1 approved these changes

2020-02-17 20:45 UTC, merged